#!/usr/bin/env python3
"""Render ContextBridge's custom public CI proof badge.

The badge is generated by the separate angusu-de mirror after its CI workflow
finishes. It is reproducibility evidence from a separate GitHub account
controlled by the same maintainer, not a third-party audit.
"""

from __future__ import annotations

import html
import json
import os
import sys
import urllib.request
from pathlib import Path


def required(name: str) -> str:
    value = os.environ.get(name, "").strip()
    if not value:
        raise SystemExit(f"missing {name}")
    return value


def github_json(url: str) -> dict:
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "ContextBridge-public-proof",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    token = os.environ.get("GITHUB_TOKEN", "").strip()
    if token:
        headers["Authorization"] = f"Bearer {token}"
    request = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(request, timeout=20) as response:
        return json.load(response)


def load_jobs(repository: str, run_id: str) -> list[dict]:
    api = os.environ.get("GITHUB_API_URL", "https://api.github.com").rstrip("/")
    jobs: list[dict] = []
    page = 1
    while True:
        payload = github_json(
            f"{api}/repos/{repository}/actions/runs/{run_id}/jobs"
            f"?per_page=100&page={page}"
        )
        batch = payload.get("jobs", [])
        if not isinstance(batch, list):
            raise SystemExit("GitHub jobs response is malformed")
        jobs.extend(item for item in batch if isinstance(item, dict))
        if len(batch) < 100:
            return jobs
        page += 1
        if page > 20:
            raise SystemExit("refusing to paginate more than 2000 CI jobs")


def status_class(conclusion: str) -> str:
    value = conclusion.lower().strip()
    if value == "success":
        return "ok"
    if value in {"failure", "timed_out", "action_required", "startup_failure"}:
        return "bad"
    if value in {"cancelled", "stale"}:
        return "warn"
    return "idle"


def render_svg(jobs: list[dict], sha: str, run_number: str, event: str) -> str:
    total = len(jobs)
    passed = sum(1 for job in jobs if job.get("conclusion") == "success")
    summary = f"{passed}/{total}" if total else "0/0"
    width = max(190, 178 + max(0, len(summary) - 3) * 7)
    rail_left = 12.0
    rail_right = width - 12.0
    rail_width = rail_right - rail_left

    visual_jobs = jobs if jobs else [{"name": "no jobs", "conclusion": ""}]
    gap = 2.0
    segment = (rail_width - gap * (len(visual_jobs) - 1)) / len(visual_jobs)
    if segment < 1.5:
        gap = 0.5
        segment = max(
            0.8,
            (rail_width - gap * (len(visual_jobs) - 1)) / len(visual_jobs),
        )

    segments: list[str] = []
    x = rail_left
    for job in visual_jobs:
        cls = status_class(str(job.get("conclusion") or ""))
        end = min(rail_right, x + segment)
        segments.append(
            f'<line class="{cls}" x1="{x:.2f}" y1="31.6" '
            f'x2="{end:.2f}" y2="31.6"/>'
        )
        x = end + gap

    job_summary = ", ".join(
        f"{job.get('name', 'job')}: {job.get('conclusion') or job.get('status') or 'unknown'}"
        for job in jobs
    )
    title = (
        "Separate-account public CI mirror (same maintainer): "
        f"{passed}/{total} jobs passed for {sha[:7]}; "
        f"run #{run_number} ({event})."
    )
    if job_summary:
        title += " " + job_summary

    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="34" '
        f'viewBox="0 0 {width} 34" role="img" aria-labelledby="title desc">'
        f'<title id="title">{html.escape(title)}</title>'
        '<desc id="desc">Custom ContextBridge public CI proof badge. '
        'The segmented lower edge represents the jobs in the latest completed '
        'mirror CI run.</desc>'
        '<style>'
        '.bg{fill:#f6f5f1;stroke:#deddd7}.fg{fill:#242421}'
        '.icon{stroke:#242421;fill:none;stroke-linecap:round;stroke-linejoin:round}'
        '.ok{stroke:#4f8a66}.bad{stroke:#b65757}.warn{stroke:#ad833c}.idle{stroke:#999990}'
        'line{stroke-width:2.6;stroke-linecap:round}'
        '@media(prefers-color-scheme:dark){'
        '.bg{fill:#242622;stroke:#44473f}.fg{fill:#f1f0e9}.icon{stroke:#f1f0e9}'
        '.ok{stroke:#70b98d}.bad{stroke:#df7676}.warn{stroke:#d5a85a}.idle{stroke:#777b72}'
        '}'
        '</style>'
        f'<rect class="bg" x="1" y="1" width="{width - 2}" height="32" rx="12"/>'
        '<g class="icon" stroke-width="1.5">'
        '<circle cx="14" cy="10" r="2"/><circle cx="24" cy="17" r="2"/>'
        '<circle cx="14" cy="24" r="2"/>'
        '<path d="M16 10h2a6 6 0 0 1 6 5M16 24h2a6 6 0 0 0 6-5"/>'
        '</g>'
        '<text class="fg" x="36" y="21.5" '
        'font-family="Arial,Helvetica,sans-serif" font-size="12.5" '
        'font-weight="600">Public proof</text>'
        f'<text class="fg" x="{width - 13}" y="21.5" text-anchor="end" '
        'font-family="Arial,Helvetica,sans-serif" font-size="12.5" '
        f'font-weight="700">{html.escape(summary)}</text>'
        + "".join(segments)
        + "</svg>"
    )


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit(
            "usage: render-public-proof-badge.py OUTPUT.svg OUTPUT.json"
        )

    repository = required("PROOF_REPOSITORY")
    run_id = required("PROOF_RUN_ID")
    run_number = required("PROOF_RUN_NUMBER")
    event = required("PROOF_RUN_EVENT")
    run_url = required("PROOF_RUN_URL")
    head_sha = required("PROOF_HEAD_SHA")

    jobs = load_jobs(repository, run_id)
    jobs.sort(key=lambda job: (int(job.get("id") or 0), str(job.get("name") or "")))

    svg_path = Path(sys.argv[1])
    json_path = Path(sys.argv[2])
    svg_path.write_text(
        render_svg(jobs, head_sha, run_number, event),
        encoding="utf-8",
    )

    metadata = {
        "claim": "separate-account CI mirror; same maintainer; not a third-party audit",
        "repository": repository,
        "run_id": int(run_id),
        "run_number": int(run_number),
        "event": event,
        "run_url": run_url,
        "head_sha": head_sha,
        "jobs_total": len(jobs),
        "jobs_success": sum(
            1 for job in jobs if job.get("conclusion") == "success"
        ),
        "jobs": [
            {
                "name": job.get("name"),
                "status": job.get("status"),
                "conclusion": job.get("conclusion"),
            }
            for job in jobs
        ],
    }
    json_path.write_text(
        json.dumps(metadata, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
